/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DailyLottery: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_entropy",
              type: "address",
              internalType: "address",
            },
            {
              name: "_rouletteContract",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "_entropyCallback",
          inputs: [
            {
              name: "sequence",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "provider",
              type: "address",
              internalType: "address",
            },
            {
              name: "randomNumber",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "addToPool",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "addToWhitelist",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "dailyPool",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dailyWhitelist",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "dayCompleted",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "draws",
          inputs: [
            {
              name: "",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "fulfilled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "winner",
              type: "address",
              internalType: "address",
            },
            {
              name: "prize",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "emergencyWithdraw",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "entropy",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IEntropyV2",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDrawDetails",
          inputs: [
            {
              name: "sequenceNumber",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct DailyLottery.DrawRequest",
              components: [
                {
                  name: "day",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "fulfilled",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "winner",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "prize",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPoolAmount",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getWhitelist",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getWhitelistSize",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isDayCompleted",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rouletteContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setRouletteContract",
          inputs: [
            {
              name: "_roulette",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startDailyDraw",
          inputs: [
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DrawRequested",
          inputs: [
            {
              name: "day",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sequenceNumber",
              type: "uint64",
              indexed: true,
              internalType: "uint64",
            },
            {
              name: "whitelistSize",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "poolAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerWhitelisted",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "day",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PoolIncreased",
          inputs: [
            {
              name: "day",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newTotal",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WinnerSelected",
          inputs: [
            {
              name: "day",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "winner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "prize",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "DayAlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "PoolEmpty",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "WhitelistEmpty",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    CryptoRoulette: {
      address: "0xa15bb66138824a1c7167f5e85b957d04dd34e468",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_entropy",
              type: "address",
              internalType: "address",
            },
            {
              name: "_lottery",
              type: "address",
              internalType: "address",
            },
            {
              name: "_ticketPrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "_entropyCallback",
          inputs: [
            {
              name: "sequence",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "provider",
              type: "address",
              internalType: "address",
            },
            {
              name: "randomNumber",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "advanceDay",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "currentDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "entropy",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IEntropyV2",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCurrentDay",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSpinDetails",
          inputs: [
            {
              name: "sequenceNumber",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CryptoRoulette.SpinRequest",
              components: [
                {
                  name: "player",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "guessedAsset",
                  type: "uint8",
                  internalType: "enum CryptoRoulette.Asset",
                },
                {
                  name: "day",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "fulfilled",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "resultAsset",
                  type: "uint8",
                  internalType: "enum CryptoRoulette.Asset",
                },
                {
                  name: "won",
                  type: "bool",
                  internalType: "bool",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTotalSpinCost",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lotteryContract",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IDailyLottery",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setTicketPrice",
          inputs: [
            {
              name: "newPrice",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "spinRoulette",
          inputs: [
            {
              name: "guess",
              type: "uint8",
              internalType: "enum CryptoRoulette.Asset",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "spins",
          inputs: [
            {
              name: "",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "guessedAsset",
              type: "uint8",
              internalType: "enum CryptoRoulette.Asset",
            },
            {
              name: "day",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "fulfilled",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "resultAsset",
              type: "uint8",
              internalType: "enum CryptoRoulette.Asset",
            },
            {
              name: "won",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ticketPrice",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawFees",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DayAdvanced",
          inputs: [
            {
              name: "newDay",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpinCompleted",
          inputs: [
            {
              name: "sequenceNumber",
              type: "uint64",
              indexed: true,
              internalType: "uint64",
            },
            {
              name: "result",
              type: "uint8",
              indexed: false,
              internalType: "enum CryptoRoulette.Asset",
            },
            {
              name: "won",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SpinRequested",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "sequenceNumber",
              type: "uint64",
              indexed: true,
              internalType: "uint64",
            },
            {
              name: "guess",
              type: "uint8",
              indexed: false,
              internalType: "enum CryptoRoulette.Asset",
            },
            {
              name: "day",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TicketPriceUpdated",
          inputs: [
            {
              name: "newPrice",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "NotEnoughFees",
          inputs: [],
        },
        {
          type: "error",
          name: "TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "Unauthorized",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    YourContract: {
      address: "0x8ce361602b935680e8dec218b820ff5056beb7af",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "greeting",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "premium",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setGreeting",
          inputs: [
            {
              name: "_newGreeting",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "totalCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userGreetingCounter",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "GreetingChange",
          inputs: [
            {
              name: "greetingSetter",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newGreeting",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "premium",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
